---
# roles/jellyfin/tasks/main.yml

- name: Create Jellyfin local configuration directories
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ quadlet_dir }}"
    - "{{ systemd_user_dir }}"
    - "{{ base_path }}/jellyfin/config"
    - "{{ base_path }}/jellyfin/cache"

- name: Mount Jellyfin NFS storage shares
  become: true
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    - { src: "/archive_media", path: "{{ media_path }}", opts: "ro,noatime,_netdev" }
    - { src: "{{ jellyfin_nfs_share }}", path: "{{ backups_path }}/jellyfin", opts: "rw,noatime,_netdev" }

- name: Create Jellyfin Quadlet definition
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    dest: "{{ quadlet_dir }}/jellyfin.container"
    content: |
      [Container]
      Image=docker.io/jellyfin/jellyfin:latest
      PublishPort=8096:8096      
      UserNS=keep-id
      Volume={{ media_path }}:/media:ro
      Volume={{ base_path }}/jellyfin/config:/config:Z
      Volume={{ base_path }}/jellyfin/cache:/cache:Z
      [Service]
      Restart=on-failure
      SuccessExitStatus=0 143
      [Install]
      WantedBy=default.target

- name: Create Jellyfin Restic password file inside backup dir
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    content: "{{ jellyfin_pass }}"
    dest: "{{ backups_path }}/jellyfin/.restic_password"
    mode: '0600'

- name: Initialize Jellyfin Restic repository
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.command: "restic -r {{ backups_path }}/jellyfin init --password-file {{ backups_path }}/jellyfin/.restic_password"
  register: restic_init
  failed_when: "(restic_init.rc != 0) and ('config file already exists' not in restic_init.stderr)"
  changed_when: "'created restic repository' in restic_init.stdout"

- name: Create Jellyfin backup systemd service
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    dest: "{{ systemd_user_dir }}/restic-jellyfin.service"
    content: |
      [Unit]
      Description=Safe Backup for Jellyfin

      [Service]
      Type=oneshot
      ExecStartPre=/usr/bin/systemctl --user stop jellyfin
      ExecStart=/usr/bin/restic -r {{ backups_path }}/jellyfin --password-file {{ backups_path }}/jellyfin/.restic_password backup {{ jellyfin_target }}
      ExecStart=/usr/bin/restic -r {{ backups_path }}/jellyfin --password-file {{ backups_path }}/jellyfin/.restic_password forget --keep-daily 30 --prune
      ExecStartPost=/usr/bin/systemctl --user start jellyfin

- name: Create Jellyfin backup systemd timer
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.copy:
    dest: "{{ systemd_user_dir }}/restic-jellyfin.timer"
    content: |
      [Unit]
      Description=Timer for Jellyfin

      [Timer]
      OnCalendar=*-*-* {{ jellyfin_time }}
      Persistent=true

      [Install]
      WantedBy=timers.target

- name: Force systemd to load configs and start Jellyfin units
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - jellyfin
    - restic-jellyfin.timer
