---
# roles/navidrome/defaults/main.yml

# --- Backups ---
navidrome_time: "02:30:00"
navidrome_target: "{{ base_path }}/navidrome"
navidrome_pass: "{{vault_navidrome_pass}}"
navidrome_nfs_share: "{{vault_navidrome_nfs_share}}"
