---
# group_vars/all/vars.yml

# --- Global ---
deploy_user: "{{vault_deploy_user}}"
base_path: "/home/{{ deploy_user }}"
quadlet_dir: "{{ base_path }}/.config/containers/systemd"
systemd_user_dir: "{{ base_path }}/.config/systemd/user"
media_path: "{{ base_path }}/media"
backups_path: "{{ base_path }}/backups"
nfs_server: "{{ vault_nfs_server }}""


