---
# roles/common/tasks/main.yml

- name: Install Podman and system dependencies
  become: true
  ansible.builtin.apt:
    name: [podman, uidmap, acl, nfs-common, restic]
    state: present
    update_cache: yes

- name: Completely stop and disable systemd-resolved to free port 53
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Point system resolver directly to DNS server
  become: true
  ansible.builtin.copy:  
    dest: /etc/resolv.conf
    content: "nameserver {{ upstream_dns_ip }}\n"
    mode: '0644'

- name: Lower unprivileged port binding limits persistently inside drop-in conf
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "0"
    sysctl_file: /etc/sysctl.d/99-rootless-ports.conf 
    sysctl_set: true
    state: present
    reload: true

- name: Enable systemd linger for deploy user
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ deploy_user }}"
  args:
    creates: "/var/lib/systemd/linger/{{ deploy_user }}"

